# ASP.NET Core (.NET Framework)

# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  batch: true
  branches:
    include:
    - master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  projects: '**/*.csproj'
  testProjects: '**/*Test*.csproj'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  major: 0
  minor: 0
  patch: 0

steps:

  - task: DotNetCoreCLI@2
    displayName: Restore nugets
    inputs:
      command: 'restore'
      projects: '$(projects)'
      feedsToUse: 'select'

  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      command: 'build'
      projects: $(projects)
      arguments: '--configuration $(buildConfiguration)'

  - task: DotNetCoreCLI@2
    displayName: Execute tests
    inputs:
      command: 'test'
      projects: $(testProjects)
      arguments: '--configuration $(buildConfiguration)'

  - task: CmdLine@2
    inputs:
      script: 'tree \ /A /F'

  #- task: DotNetCoreCLI@2
  #  displayName: 'Create packed NuGet files'
  #  inputs:
  #    command: 'pack'
  #    packagesToPack: '**/*Api.csproj;!**/*Tests.csproj'
  #    versioningScheme: 'off'

  #- task: DotNetCoreCLI@2
  #  inputs:
  #    command: 'pack'
  #    packagesToPack: '**/*API.nuspec'
  #    nobuild: true
  #    versioningScheme: 'off'

  - task: DotNetCoreCLI@2
    displayName: 'dotnet custom'
    inputs:
      command: custom
      projects: '**/SuperMarket.WebAPI.csproj'
      custom: pack
      arguments: '-p:NuspecFile=~SuperMarket/SuperMarket.WebAPI.nuspec -p:NuspecBasePath=~SuperMarket/nuget'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
      publishLocation: 'Container'
